"""Implementation of statechart statechart.
Generated by YAKINDU Statechart Tools code generator.
"""

import queue
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))

class Statechart:
	"""Implementation of the state machine Statechart.
	"""

	class State:
		""" State Enum
		"""
		(
			main_region_at__home,
			main_region_at__work,
			main_region_at__work_working_at__shift,
			main_region_at__work_working_at__shift_shift_unloading,
			main_region_at__work_working_at__shift_shift_unloading_main_at_stock,
			main_region_at__work_working_at__shift_shift_unloading_main_at_truck,
			main_region_at__work_working_at__shift_shift_unloading_main_at_stock_carrying,
			main_region_at__work_working_at__shift_shift_unloading_main_at_truck_carrying,
			main_region_at__work_working_at__shift_shift_assembly,
			main_region_at__work_working_at__shift_shift_assembly_r1_at_stock,
			main_region_at__work_working_at__shift_shift_assembly_r1_assemble,
			main_region_at__work_working_at__shift_shift_loading,
			main_region_at__work_working_at__shift_shift_loading_r1_at_truck,
			main_region_at__work_working_at__shift_shift_loading_r1_at_stock,
			main_region_at__work_working_at__shift_shift_loading_r1_at_truck_carrying,
			main_region_at__work_working_at__shift_shift_loading_r1_at_stock_carrying,
			main_region_at__work_working_at__shift_energy_tiring,
			main_region_at__work_working_at__shift_button_button_released,
			main_region_at__work_working_at__shift_button_button_pressed,
			main_region_at__work_working_at__shift_button_button_activated,
			main_region_at__work_working_toilet__break,
			main_region_at__work_working_leave__day,
			main_region_at__work_working_grace__period,
			main_region_at__work_working_grace__period_r1_alternative__chosen,
			main_region_at__work_working_grace__period_r1_in_grace,
			main_region_shift_end,
			main_region_leave_tired,
			null_state
		) = range(28)
	
	
	class Util:
		"""Implementation of scope Util.
		"""
		
		def __init__(self, statemachine):
			self.operation_callback = None
			
			self.statemachine = statemachine
		
	
	class Employee:
		"""Implementation of scope Employee.
		"""
		
		def __init__(self, statemachine):
			self.go_to_work = None
			self.go_home = None
			self.shift_clicked = None
			self.shift_clicked_value = None
			self.operation_callback = None
			
			self.statemachine = statemachine
		
		def raise_go_to_work(self):
			"""Raise method for event go_to_work.
			"""
			self.statemachine.in_event_queue.put(self.raise_go_to_work_call)
			self.statemachine.run_cycle()
		
		def raise_go_to_work_call(self):
			"""Raise callback for event go_to_work.
			"""
			self.go_to_work = True
		
		def raise_go_home(self):
			"""Raise method for event go_home.
			"""
			self.statemachine.in_event_queue.put(self.raise_go_home_call)
			self.statemachine.run_cycle()
		
		def raise_go_home_call(self):
			"""Raise callback for event go_home.
			"""
			self.go_home = True
		
		def raise_shift_clicked(self, value):
			"""Raise method for event shift_clicked.
			"""
			self.statemachine.in_event_queue.put(lambda: self.raise_shift_clicked_call(value))
			self.statemachine.run_cycle()
		
		def raise_shift_clicked_call(self, value):
			"""Raise callback for event shift_clicked.
			"""
			self.shift_clicked = True
			self.shift_clicked_value = value
		
	
	class Factory:
		"""Implementation of scope Factory.
		"""
		
		def __init__(self, statemachine):
			self.operation_callback = None
			
			self.statemachine = statemachine
		
	
	class Ui:
		"""Implementation of scope Ui.
		"""
		
		def __init__(self, statemachine):
			self.action_pressed = None
			self.action_pressed_value = None
			self.action_released = None
			self.action_released_value = None
			self.operation_callback = None
			
			self.statemachine = statemachine
		
		def raise_action_pressed(self, value):
			"""Raise method for event action_pressed.
			"""
			self.statemachine.in_event_queue.put(lambda: self.raise_action_pressed_call(value))
			self.statemachine.run_cycle()
		
		def raise_action_pressed_call(self, value):
			"""Raise callback for event action_pressed.
			"""
			self.action_pressed = True
			self.action_pressed_value = value
		
		def raise_action_released(self, value):
			"""Raise method for event action_released.
			"""
			self.statemachine.in_event_queue.put(lambda: self.raise_action_released_call(value))
			self.statemachine.run_cycle()
		
		def raise_action_released_call(self, value):
			"""Raise callback for event action_released.
			"""
			self.action_released = True
			self.action_released_value = value
		
	
	def __init__(self):
		""" Declares all necessary variables including list of states, histories etc. 
		"""
		self.util = Statechart.Util(self)
		self.employee = Statechart.Employee(self)
		self.factory = Statechart.Factory(self)
		self.ui = Statechart.Ui(self)
		
		self.in_event_queue = queue.Queue()
		self.__assigned_shift = None
		self.__current_action = None
		
		# enumeration of all states:
		self.__State = Statechart.State
		self.__state_conf_vector_changed = None
		self.__next_state_index = None
		self.__state_vector = [None] * 3
		for __state_index in range(3):
			self.__state_vector[__state_index] = self.State.null_state
		
		# for timed statechart:
		self.timer_service = None
		self.__time_events = [None] * 8
		
		# history vector:
		self.__history_vector = [None] * 1
		for __history_index in range(1):
			self.__history_vector[__history_index] = self.State.null_state
		
		# initializations:
		self.__assigned_shift = 0
		self.__current_action = ""
		self.__is_executing = False
	
	def is_active(self):
		"""Checks if the state machine is active.
		"""
		return self.__state_vector[0] is not self.__State.null_state or self.__state_vector[1] is not self.__State.null_state or self.__state_vector[2] is not self.__State.null_state
	
	def is_final(self):
		"""Checks if the statemachine is final.
		Always returns 'false' since this state machine can never become final.
		"""
		return False
			
	def is_state_active(self, state):
		"""Checks if the state is currently active.
		"""
		s = state
		if s == self.__State.main_region_at__home:
			return self.__state_vector[0] == self.__State.main_region_at__home
		if s == self.__State.main_region_at__work:
			return (self.__state_vector[0] >= self.__State.main_region_at__work)\
				and (self.__state_vector[0] <= self.__State.main_region_at__work_working_grace__period_r1_in_grace)
		if s == self.__State.main_region_at__work_working_at__shift:
			return (self.__state_vector[0] >= self.__State.main_region_at__work_working_at__shift)\
				and (self.__state_vector[0] <= self.__State.main_region_at__work_working_at__shift_button_button_activated)
		if s == self.__State.main_region_at__work_working_at__shift_shift_unloading:
			return (self.__state_vector[0] >= self.__State.main_region_at__work_working_at__shift_shift_unloading)\
				and (self.__state_vector[0] <= self.__State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck_carrying)
		if s == self.__State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock
		if s == self.__State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck
		if s == self.__State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock_carrying:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock_carrying
		if s == self.__State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck_carrying:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck_carrying
		if s == self.__State.main_region_at__work_working_at__shift_shift_assembly:
			return (self.__state_vector[0] >= self.__State.main_region_at__work_working_at__shift_shift_assembly)\
				and (self.__state_vector[0] <= self.__State.main_region_at__work_working_at__shift_shift_assembly_r1_assemble)
		if s == self.__State.main_region_at__work_working_at__shift_shift_assembly_r1_at_stock:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_at__shift_shift_assembly_r1_at_stock
		if s == self.__State.main_region_at__work_working_at__shift_shift_assembly_r1_assemble:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_at__shift_shift_assembly_r1_assemble
		if s == self.__State.main_region_at__work_working_at__shift_shift_loading:
			return (self.__state_vector[0] >= self.__State.main_region_at__work_working_at__shift_shift_loading)\
				and (self.__state_vector[0] <= self.__State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock_carrying)
		if s == self.__State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck
		if s == self.__State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock
		if s == self.__State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck_carrying:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck_carrying
		if s == self.__State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock_carrying:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock_carrying
		if s == self.__State.main_region_at__work_working_at__shift_energy_tiring:
			return self.__state_vector[1] == self.__State.main_region_at__work_working_at__shift_energy_tiring
		if s == self.__State.main_region_at__work_working_at__shift_button_button_released:
			return self.__state_vector[2] == self.__State.main_region_at__work_working_at__shift_button_button_released
		if s == self.__State.main_region_at__work_working_at__shift_button_button_pressed:
			return self.__state_vector[2] == self.__State.main_region_at__work_working_at__shift_button_button_pressed
		if s == self.__State.main_region_at__work_working_at__shift_button_button_activated:
			return self.__state_vector[2] == self.__State.main_region_at__work_working_at__shift_button_button_activated
		if s == self.__State.main_region_at__work_working_toilet__break:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_toilet__break
		if s == self.__State.main_region_at__work_working_leave__day:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_leave__day
		if s == self.__State.main_region_at__work_working_grace__period:
			return (self.__state_vector[0] >= self.__State.main_region_at__work_working_grace__period)\
				and (self.__state_vector[0] <= self.__State.main_region_at__work_working_grace__period_r1_in_grace)
		if s == self.__State.main_region_at__work_working_grace__period_r1_alternative__chosen:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_grace__period_r1_alternative__chosen
		if s == self.__State.main_region_at__work_working_grace__period_r1_in_grace:
			return self.__state_vector[0] == self.__State.main_region_at__work_working_grace__period_r1_in_grace
		if s == self.__State.main_region_shift_end:
			return self.__state_vector[0] == self.__State.main_region_shift_end
		if s == self.__State.main_region_leave_tired:
			return self.__state_vector[0] == self.__State.main_region_leave_tired
		return False
		
	def time_elapsed(self, event_id):
		"""Add time events to in event queue
		"""
		if event_id in range(8):
			self.in_event_queue.put(lambda: self.raise_time_event(event_id))
			self.run_cycle()
	
	def raise_time_event(self, event_id):
		"""Raise timed events using the event_id.
		"""
		self.__time_events[event_id] = True
	
	def __execute_queued_event(self, func):
		func()
	
	def __get_next_event(self):
		if not self.in_event_queue.empty():
			return self.in_event_queue.get()
		return None
	
	
	def __check_main_region__at__work_working__at__shift_shift__choice_0_tr0_tr0(self):
		""".
		"""
		return self.__assigned_shift == 1
		
	def __check_main_region__at__work_working__at__shift_shift__choice_0_tr1_tr1(self):
		""".
		"""
		return self.__assigned_shift == 2
		
	def __effect_main_region__at__work_working__at__shift_shift__choice_0_tr0(self):
		""".
		"""
		self.__enter_sequence_main_region__at__work_working__at__shift_shift__assembly_default()
		
	def __effect_main_region__at__work_working__at__shift_shift__choice_0_tr1(self):
		""".
		"""
		self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_default()
		
	def __effect_main_region__at__work_working__at__shift_shift__choice_0_tr2(self):
		""".
		"""
		self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_default()
		
	def __entry_action_main_region__at__home(self):
		"""Entry action for state 'At Home'..
		"""
		self.ui.operation_callback.shifts_hide()
		self.ui.operation_callback.set_msg("At home")
		self.employee.operation_callback.increase_energy(50)
		
	def __entry_action_main_region__at__work(self):
		"""Entry action for state 'At Work'..
		"""
		self.timer_service.set_timer(self, 0, (14 * 1000), False)
		
	def __entry_action_main_region__at__work_working__at__shift(self):
		"""Entry action for state 'At Shift'..
		"""
		self.ui.operation_callback.shift_highlight_clear()
		self.ui.operation_callback.shift_highlight_active(self.__assigned_shift)
		
	def __entry_action_main_region__at__work_working__at__shift_shift__unloading(self):
		"""Entry action for state 'Unloading'..
		"""
		self.ui.operation_callback.set_msg("Unloading Shift")
		self.ui.operation_callback.set_msg("Unloading Shift")
		self.ui.operation_callback.set_msg("Unloading Shift")
		
	def __entry_action_main_region__at__work_working__at__shift_shift__unloading_main__at_stock(self):
		"""Entry action for state 'AtStock'..
		"""
		self.ui.operation_callback.set_actions("Walk,Toilet Break")
		self.ui.operation_callback.set_msg("In stock.\n Not carrying anything")
		self.__current_action = ""
		
	def __entry_action_main_region__at__work_working__at__shift_shift__unloading_main__at_truck(self):
		"""Entry action for state 'AtTruck'..
		"""
		self.ui.operation_callback.set_actions("Walk,Pickup")
		self.ui.operation_callback.set_msg("At truck. \n Not carrying anything")
		self.__current_action = ""
		
	def __entry_action_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying(self):
		"""Entry action for state 'AtStockCarrying'..
		"""
		self.ui.operation_callback.set_actions("Walk,Drop")
		self.ui.operation_callback.set_msg("In stock.\n Carrying material")
		self.__current_action = ""
		self.ui.operation_callback.set_actions("Walk,Drop")
		self.ui.operation_callback.set_msg("In stock.\n Carrying material")
		self.__current_action = ""
		self.ui.operation_callback.set_actions("Walk,Drop")
		self.ui.operation_callback.set_msg("In stock.\n Carrying material")
		self.__current_action = ""
		
	def __entry_action_main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying(self):
		"""Entry action for state 'AtTruckCarrying'..
		"""
		self.ui.operation_callback.set_actions("Walk")
		self.ui.operation_callback.set_msg("At truck.\n Carrying material")
		self.__current_action = ""
		self.ui.operation_callback.set_actions("Walk")
		self.ui.operation_callback.set_msg("At truck.\n Carrying material")
		self.__current_action = ""
		self.ui.operation_callback.set_actions("Walk")
		self.ui.operation_callback.set_msg("At truck.\n Carrying material")
		self.__current_action = ""
		
	def __entry_action_main_region__at__work_working__at__shift_shift__assembly(self):
		"""Entry action for state 'Assembly'..
		"""
		self.ui.operation_callback.set_msg("Assembly Shift")
		self.ui.operation_callback.set_msg("Assembly Shift")
		self.ui.operation_callback.set_msg("Assembly Shift")
		
	def __entry_action_main_region__at__work_working__at__shift_shift__assembly_r1__at_stock(self):
		"""Entry action for state 'AtStock'..
		"""
		self.ui.operation_callback.set_actions("Assemble")
		self.ui.operation_callback.set_msg("At Assembly.")
		self.ui.operation_callback.set_actions("Assemble")
		self.ui.operation_callback.set_msg("At Assembly.")
		self.ui.operation_callback.set_actions("Assemble")
		self.ui.operation_callback.set_msg("At Assembly.")
		
	def __entry_action_main_region__at__work_working__at__shift_shift__assembly_r1__assemble(self):
		"""Entry action for state 'Assemble'..
		"""
		self.timer_service.set_timer(self, 1, (1 * 1000), False)
		self.factory.operation_callback.increase_finished(1)
		self.factory.operation_callback.increase_material(-1)
		self.__current_action = ""
		self.ui.operation_callback.set_msg("Assembling")
		
	def __entry_action_main_region__at__work_working__at__shift_shift__loading(self):
		"""Entry action for state 'Loading'..
		"""
		self.ui.operation_callback.set_msg("Loading Shift")
		self.ui.operation_callback.set_msg("Loading Shift")
		self.ui.operation_callback.set_msg("Loading Shift")
		
	def __entry_action_main_region__at__work_working__at__shift_shift__loading_r1__at_truck(self):
		"""Entry action for state 'AtTruck'..
		"""
		self.ui.operation_callback.set_actions("Walk")
		self.ui.operation_callback.set_msg("At truck.\n Not carrying anything")
		self.__current_action = ""
		
	def __entry_action_main_region__at__work_working__at__shift_shift__loading_r1__at_stock(self):
		"""Entry action for state 'AtStock'..
		"""
		self.ui.operation_callback.set_actions("Walk,Pickup,Toilet Break")
		self.ui.operation_callback.set_msg("In stock. \n Not carrying anything")
		self.__current_action = ""
		
	def __entry_action_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying(self):
		"""Entry action for state 'AtTruckCarrying'..
		"""
		self.ui.operation_callback.set_actions("Walk,Drop")
		self.ui.operation_callback.set_msg("At truck. \n Carrying product")
		self.__current_action = ""
		
	def __entry_action_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying(self):
		"""Entry action for state 'AtStockCarrying'..
		"""
		self.ui.operation_callback.set_actions("Walk")
		self.ui.operation_callback.set_msg("In stock.\n Carrying product")
		self.__current_action = ""
		
	def __entry_action_main_region__at__work_working__at__shift_energy__tiring(self):
		"""Entry action for state 'Tiring'..
		"""
		self.timer_service.set_timer(self, 2, (1 * 1000), False)
		
	def __entry_action_main_region__at__work_working__at__shift_button_button_pressed(self):
		"""Entry action for state 'buttonPressed'..
		"""
		self.timer_service.set_timer(self, 3, 500, False)
		
	def __entry_action_main_region__at__work_working__at__shift_button_button_activated(self):
		"""Entry action for state 'buttonActivated'..
		"""
		self.__current_action = self.ui.action_pressed_value
		self.__current_action = self.ui.action_pressed_value
		
	def __entry_action_main_region__at__work_working__toilet__break(self):
		"""Entry action for state 'Toilet Break'..
		"""
		self.ui.operation_callback.set_actions("Done")
		self.ui.operation_callback.set_msg("In toilet.")
		self.ui.operation_callback.set_actions("Done")
		self.ui.operation_callback.set_msg("In toilet.")
		
	def __entry_action_main_region__at__work_working__leave__day(self):
		"""Entry action for state 'Leave Day'..
		"""
		self.timer_service.set_timer(self, 4, (2 * 1000), False)
		self.ui.operation_callback.set_msg("Going Home")
		self.ui.operation_callback.shift_highlight_clear()
		self.ui.operation_callback.set_msg("Going Home")
		self.ui.operation_callback.shift_highlight_clear()
		
	def __entry_action_main_region__at__work_working__grace__period(self):
		"""Entry action for state 'Grace Period'..
		"""
		self.timer_service.set_timer(self, 5, (4 * 1000), False)
		self.ui.operation_callback.set_msg("Grace period...")
		self.ui.operation_callback.shifts_show()
		self.ui.operation_callback.set_msg("Grace period...")
		self.ui.operation_callback.shifts_show()
		
	def __entry_action_main_region__at__work_working__grace__period_r1__alternative__chosen(self):
		"""Entry action for state 'Alternative Chosen'..
		"""
		self.__assigned_shift = self.employee.shift_clicked_value
		self.ui.operation_callback.set_msg("Chose another shift")
		self.ui.operation_callback.shift_highlight_clear()
		self.ui.operation_callback.shift_highlight_assigned(self.__assigned_shift)
		self.__assigned_shift = self.employee.shift_clicked_value
		self.ui.operation_callback.set_msg("Chose another shift")
		self.ui.operation_callback.shift_highlight_clear()
		self.ui.operation_callback.shift_highlight_assigned(self.__assigned_shift)
		
	def __entry_action_main_region__at__work_working__grace__period_r1_in_grace(self):
		"""Entry action for state 'inGrace'..
		"""
		self.__assigned_shift = self.util.operation_callback.get_random_integer(3)
		self.ui.operation_callback.shift_highlight_assigned(self.__assigned_shift)
		self.__assigned_shift = self.util.operation_callback.get_random_integer(3)
		self.ui.operation_callback.shift_highlight_assigned(self.__assigned_shift)
		
	def __entry_action_main_region__shift_end(self):
		"""Entry action for state 'ShiftEnd'..
		"""
		self.timer_service.set_timer(self, 6, (0 * 1000), False)
		self.employee.operation_callback.increase_pay(10)
		self.ui.operation_callback.set_actions("")
		self.ui.operation_callback.set_msg("Ending shift")
		
	def __entry_action_main_region__leave_tired(self):
		"""Entry action for state 'LeaveTired'..
		"""
		self.timer_service.set_timer(self, 7, (2 * 1000), False)
		self.ui.operation_callback.set_msg("Going Home, I\'m too tired")
		self.ui.operation_callback.shift_highlight_clear()
		
	def __exit_action_main_region__at__work(self):
		"""Exit action for state 'At Work'..
		"""
		self.timer_service.unset_timer(self, 0)
		
	def __exit_action_main_region__at__work_working__at__shift_shift__assembly_r1__assemble(self):
		"""Exit action for state 'Assemble'..
		"""
		self.timer_service.unset_timer(self, 1)
		
	def __exit_action_main_region__at__work_working__at__shift_energy__tiring(self):
		"""Exit action for state 'Tiring'..
		"""
		self.timer_service.unset_timer(self, 2)
		
	def __exit_action_main_region__at__work_working__at__shift_button_button_pressed(self):
		"""Exit action for state 'buttonPressed'..
		"""
		self.timer_service.unset_timer(self, 3)
		
	def __exit_action_main_region__at__work_working__leave__day(self):
		"""Exit action for state 'Leave Day'..
		"""
		self.timer_service.unset_timer(self, 4)
		
	def __exit_action_main_region__at__work_working__grace__period(self):
		"""Exit action for state 'Grace Period'..
		"""
		self.timer_service.unset_timer(self, 5)
		
	def __exit_action_main_region__shift_end(self):
		"""Exit action for state 'ShiftEnd'..
		"""
		self.timer_service.unset_timer(self, 6)
		
	def __exit_action_main_region__leave_tired(self):
		"""Exit action for state 'LeaveTired'..
		"""
		self.timer_service.unset_timer(self, 7)
		
	def __enter_sequence_main_region__at__home_default(self):
		"""'default' enter sequence for state At Home.
		"""
		self.__entry_action_main_region__at__home()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__home
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_default(self):
		"""'default' enter sequence for state At Work.
		"""
		self.__entry_action_main_region__at__work()
		self.__enter_sequence_main_region__at__work_working_default()
		
	def __enter_sequence_main_region__at__work_working__at__shift_default(self):
		"""'default' enter sequence for state At Shift.
		"""
		self.__entry_action_main_region__at__work_working__at__shift()
		self.__enter_sequence_main_region__at__work_working__at__shift_shift_default()
		self.__enter_sequence_main_region__at__work_working__at__shift_energy_default()
		self.__enter_sequence_main_region__at__work_working__at__shift_button_default()
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__unloading_default(self):
		"""'default' enter sequence for state Unloading.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__unloading()
		self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main_default()
		self.__history_vector[0] = self.__state_vector[0]
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_default(self):
		"""'default' enter sequence for state AtStock.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__unloading_main__at_stock()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck_default(self):
		"""'default' enter sequence for state AtTruck.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__unloading_main__at_truck()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying_default(self):
		"""'default' enter sequence for state AtStockCarrying.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock_carrying
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying_default(self):
		"""'default' enter sequence for state AtTruckCarrying.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck_carrying
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__assembly_default(self):
		"""'default' enter sequence for state Assembly.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__assembly()
		self.__enter_sequence_main_region__at__work_working__at__shift_shift__assembly_r1_default()
		self.__history_vector[0] = self.__state_vector[0]
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__at_stock_default(self):
		"""'default' enter sequence for state AtStock.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__assembly_r1__at_stock()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_at__shift_shift_assembly_r1_at_stock
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__assemble_default(self):
		"""'default' enter sequence for state Assemble.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__assembly_r1__assemble()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_at__shift_shift_assembly_r1_assemble
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__loading_default(self):
		"""'default' enter sequence for state Loading.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__loading()
		self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1_default()
		self.__history_vector[0] = self.__state_vector[0]
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_default(self):
		"""'default' enter sequence for state AtTruck.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__loading_r1__at_truck()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_default(self):
		"""'default' enter sequence for state AtStock.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__loading_r1__at_stock()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying_default(self):
		"""'default' enter sequence for state AtTruckCarrying.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck_carrying
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying_default(self):
		"""'default' enter sequence for state AtStockCarrying.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock_carrying
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_energy__tiring_default(self):
		"""'default' enter sequence for state Tiring.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_energy__tiring()
		self.__next_state_index = 1
		self.__state_vector[1] = self.State.main_region_at__work_working_at__shift_energy_tiring
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_button_button_released_default(self):
		"""'default' enter sequence for state buttonReleased.
		"""
		self.__next_state_index = 2
		self.__state_vector[2] = self.State.main_region_at__work_working_at__shift_button_button_released
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_button_button_pressed_default(self):
		"""'default' enter sequence for state buttonPressed.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_button_button_pressed()
		self.__next_state_index = 2
		self.__state_vector[2] = self.State.main_region_at__work_working_at__shift_button_button_pressed
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__at__shift_button_button_activated_default(self):
		"""'default' enter sequence for state buttonActivated.
		"""
		self.__entry_action_main_region__at__work_working__at__shift_button_button_activated()
		self.__next_state_index = 2
		self.__state_vector[2] = self.State.main_region_at__work_working_at__shift_button_button_activated
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__toilet__break_default(self):
		"""'default' enter sequence for state Toilet Break.
		"""
		self.__entry_action_main_region__at__work_working__toilet__break()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_toilet__break
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__leave__day_default(self):
		"""'default' enter sequence for state Leave Day.
		"""
		self.__entry_action_main_region__at__work_working__leave__day()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_leave__day
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__grace__period_default(self):
		"""'default' enter sequence for state Grace Period.
		"""
		self.__entry_action_main_region__at__work_working__grace__period()
		self.__enter_sequence_main_region__at__work_working__grace__period_r1_default()
		
	def __enter_sequence_main_region__at__work_working__grace__period_r1__alternative__chosen_default(self):
		"""'default' enter sequence for state Alternative Chosen.
		"""
		self.__entry_action_main_region__at__work_working__grace__period_r1__alternative__chosen()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_grace__period_r1_alternative__chosen
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__at__work_working__grace__period_r1_in_grace_default(self):
		"""'default' enter sequence for state inGrace.
		"""
		self.__entry_action_main_region__at__work_working__grace__period_r1_in_grace()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_at__work_working_grace__period_r1_in_grace
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__shift_end_default(self):
		"""'default' enter sequence for state ShiftEnd.
		"""
		self.__entry_action_main_region__shift_end()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_shift_end
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region__leave_tired_default(self):
		"""'default' enter sequence for state LeaveTired.
		"""
		self.__entry_action_main_region__leave_tired()
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.main_region_leave_tired
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_default(self):
		"""'default' enter sequence for region main region.
		"""
		self.__react_main_region__entry__default()
		
	def __enter_sequence_main_region__at__work_working_default(self):
		"""'default' enter sequence for region working.
		"""
		self.__react_main_region__at__work_working__entry__default()
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift_default(self):
		"""'default' enter sequence for region shift.
		"""
		self.__react_main_region__at__work_working__at__shift_shift__entry__default()
		
	def __shallow_enter_sequence_main_region__at__work_working__at__shift_shift(self):
		"""shallow enterSequence with history in child shift.
		"""
		state = self.__history_vector[0]
		if state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock:
			self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_default()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck:
			self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_default()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock_carrying:
			self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_default()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck_carrying:
			self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_default()
		elif state == self.State.main_region_at__work_working_at__shift_shift_assembly_r1_at_stock:
			self.__enter_sequence_main_region__at__work_working__at__shift_shift__assembly_default()
		elif state == self.State.main_region_at__work_working_at__shift_shift_assembly_r1_assemble:
			self.__enter_sequence_main_region__at__work_working__at__shift_shift__assembly_default()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck:
			self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_default()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock:
			self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_default()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck_carrying:
			self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_default()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock_carrying:
			self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_default()
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main_default(self):
		"""'default' enter sequence for region main.
		"""
		self.__react_main_region__at__work_working__at__shift_shift__unloading_main__entry__default()
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__assembly_r1_default(self):
		"""'default' enter sequence for region r1.
		"""
		self.__react_main_region__at__work_working__at__shift_shift__assembly_r1__entry__default()
		
	def __enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1_default(self):
		"""'default' enter sequence for region r1.
		"""
		self.__react_main_region__at__work_working__at__shift_shift__loading_r1__entry__default()
		
	def __enter_sequence_main_region__at__work_working__at__shift_energy_default(self):
		"""'default' enter sequence for region energy.
		"""
		self.__react_main_region__at__work_working__at__shift_energy__entry__default()
		
	def __enter_sequence_main_region__at__work_working__at__shift_button_default(self):
		"""'default' enter sequence for region button.
		"""
		self.__react_main_region__at__work_working__at__shift_button__entry__default()
		
	def __enter_sequence_main_region__at__work_working__grace__period_r1_default(self):
		"""'default' enter sequence for region r1.
		"""
		self.__react_main_region__at__work_working__grace__period_r1__entry__default()
		
	def __exit_sequence_main_region__at__home(self):
		"""Default exit sequence for state At Home.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__at__work(self):
		"""Default exit sequence for state At Work.
		"""
		self.__exit_sequence_main_region__at__work_working()
		self.__exit_action_main_region__at__work()
		
	def __exit_sequence_main_region__at__work_working__at__shift(self):
		"""Default exit sequence for state At Shift.
		"""
		self.__exit_sequence_main_region__at__work_working__at__shift_shift()
		self.__exit_sequence_main_region__at__work_working__at__shift_energy()
		self.__exit_sequence_main_region__at__work_working__at__shift_button()
		
	def __exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock(self):
		"""Default exit sequence for state AtStock.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck(self):
		"""Default exit sequence for state AtTruck.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying(self):
		"""Default exit sequence for state AtStockCarrying.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying(self):
		"""Default exit sequence for state AtTruckCarrying.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__at_stock(self):
		"""Default exit sequence for state AtStock.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__assemble(self):
		"""Default exit sequence for state Assemble.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		self.__exit_action_main_region__at__work_working__at__shift_shift__assembly_r1__assemble()
		
	def __exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck(self):
		"""Default exit sequence for state AtTruck.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock(self):
		"""Default exit sequence for state AtStock.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying(self):
		"""Default exit sequence for state AtTruckCarrying.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying(self):
		"""Default exit sequence for state AtStockCarrying.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__at__shift_energy__tiring(self):
		"""Default exit sequence for state Tiring.
		"""
		self.__next_state_index = 1
		self.__state_vector[1] = self.State.null_state
		self.__exit_action_main_region__at__work_working__at__shift_energy__tiring()
		
	def __exit_sequence_main_region__at__work_working__at__shift_button_button_released(self):
		"""Default exit sequence for state buttonReleased.
		"""
		self.__next_state_index = 2
		self.__state_vector[2] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__at__shift_button_button_pressed(self):
		"""Default exit sequence for state buttonPressed.
		"""
		self.__next_state_index = 2
		self.__state_vector[2] = self.State.null_state
		self.__exit_action_main_region__at__work_working__at__shift_button_button_pressed()
		
	def __exit_sequence_main_region__at__work_working__at__shift_button_button_activated(self):
		"""Default exit sequence for state buttonActivated.
		"""
		self.__next_state_index = 2
		self.__state_vector[2] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__toilet__break(self):
		"""Default exit sequence for state Toilet Break.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__leave__day(self):
		"""Default exit sequence for state Leave Day.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		self.__exit_action_main_region__at__work_working__leave__day()
		
	def __exit_sequence_main_region__at__work_working__grace__period(self):
		"""Default exit sequence for state Grace Period.
		"""
		self.__exit_sequence_main_region__at__work_working__grace__period_r1()
		self.__exit_action_main_region__at__work_working__grace__period()
		
	def __exit_sequence_main_region__at__work_working__grace__period_r1__alternative__chosen(self):
		"""Default exit sequence for state Alternative Chosen.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__at__work_working__grace__period_r1_in_grace(self):
		"""Default exit sequence for state inGrace.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region__shift_end(self):
		"""Default exit sequence for state ShiftEnd.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		self.__exit_action_main_region__shift_end()
		
	def __exit_sequence_main_region__leave_tired(self):
		"""Default exit sequence for state LeaveTired.
		"""
		self.__next_state_index = 0
		self.__state_vector[0] = self.State.null_state
		self.__exit_action_main_region__leave_tired()
		
	def __exit_sequence_main_region(self):
		"""Default exit sequence for region main region.
		"""
		state = self.__state_vector[0]
		if state == self.State.main_region_at__home:
			self.__exit_sequence_main_region__at__home()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock_carrying:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck_carrying:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying()
		elif state == self.State.main_region_at__work_working_at__shift_shift_assembly_r1_at_stock:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__at_stock()
		elif state == self.State.main_region_at__work_working_at__shift_shift_assembly_r1_assemble:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__assemble()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck_carrying:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock_carrying:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying()
		elif state == self.State.main_region_at__work_working_toilet__break:
			self.__exit_sequence_main_region__at__work_working__toilet__break()
			self.__exit_action_main_region__at__work()
		elif state == self.State.main_region_at__work_working_leave__day:
			self.__exit_sequence_main_region__at__work_working__leave__day()
			self.__exit_action_main_region__at__work()
		elif state == self.State.main_region_at__work_working_grace__period_r1_alternative__chosen:
			self.__exit_sequence_main_region__at__work_working__grace__period_r1__alternative__chosen()
			self.__exit_action_main_region__at__work_working__grace__period()
			self.__exit_action_main_region__at__work()
		elif state == self.State.main_region_at__work_working_grace__period_r1_in_grace:
			self.__exit_sequence_main_region__at__work_working__grace__period_r1_in_grace()
			self.__exit_action_main_region__at__work_working__grace__period()
			self.__exit_action_main_region__at__work()
		elif state == self.State.main_region_shift_end:
			self.__exit_sequence_main_region__shift_end()
		elif state == self.State.main_region_leave_tired:
			self.__exit_sequence_main_region__leave_tired()
		state = self.__state_vector[1]
		if state == self.State.main_region_at__work_working_at__shift_energy_tiring:
			self.__exit_sequence_main_region__at__work_working__at__shift_energy__tiring()
		state = self.__state_vector[2]
		if state == self.State.main_region_at__work_working_at__shift_button_button_released:
			self.__exit_sequence_main_region__at__work_working__at__shift_button_button_released()
			self.__exit_action_main_region__at__work()
		elif state == self.State.main_region_at__work_working_at__shift_button_button_pressed:
			self.__exit_sequence_main_region__at__work_working__at__shift_button_button_pressed()
			self.__exit_action_main_region__at__work()
		elif state == self.State.main_region_at__work_working_at__shift_button_button_activated:
			self.__exit_sequence_main_region__at__work_working__at__shift_button_button_activated()
			self.__exit_action_main_region__at__work()
		
	def __exit_sequence_main_region__at__work_working(self):
		"""Default exit sequence for region working.
		"""
		state = self.__state_vector[0]
		if state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock_carrying:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck_carrying:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying()
		elif state == self.State.main_region_at__work_working_at__shift_shift_assembly_r1_at_stock:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__at_stock()
		elif state == self.State.main_region_at__work_working_at__shift_shift_assembly_r1_assemble:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__assemble()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck_carrying:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock_carrying:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying()
		elif state == self.State.main_region_at__work_working_toilet__break:
			self.__exit_sequence_main_region__at__work_working__toilet__break()
		elif state == self.State.main_region_at__work_working_leave__day:
			self.__exit_sequence_main_region__at__work_working__leave__day()
		elif state == self.State.main_region_at__work_working_grace__period_r1_alternative__chosen:
			self.__exit_sequence_main_region__at__work_working__grace__period_r1__alternative__chosen()
			self.__exit_action_main_region__at__work_working__grace__period()
		elif state == self.State.main_region_at__work_working_grace__period_r1_in_grace:
			self.__exit_sequence_main_region__at__work_working__grace__period_r1_in_grace()
			self.__exit_action_main_region__at__work_working__grace__period()
		state = self.__state_vector[1]
		if state == self.State.main_region_at__work_working_at__shift_energy_tiring:
			self.__exit_sequence_main_region__at__work_working__at__shift_energy__tiring()
		state = self.__state_vector[2]
		if state == self.State.main_region_at__work_working_at__shift_button_button_released:
			self.__exit_sequence_main_region__at__work_working__at__shift_button_button_released()
		elif state == self.State.main_region_at__work_working_at__shift_button_button_pressed:
			self.__exit_sequence_main_region__at__work_working__at__shift_button_button_pressed()
		elif state == self.State.main_region_at__work_working_at__shift_button_button_activated:
			self.__exit_sequence_main_region__at__work_working__at__shift_button_button_activated()
		
	def __exit_sequence_main_region__at__work_working__at__shift_shift(self):
		"""Default exit sequence for region shift.
		"""
		state = self.__state_vector[0]
		if state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock_carrying:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying()
		elif state == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck_carrying:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying()
		elif state == self.State.main_region_at__work_working_at__shift_shift_assembly_r1_at_stock:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__at_stock()
		elif state == self.State.main_region_at__work_working_at__shift_shift_assembly_r1_assemble:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__assemble()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck_carrying:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying()
		elif state == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock_carrying:
			self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying()
		
	def __exit_sequence_main_region__at__work_working__at__shift_energy(self):
		"""Default exit sequence for region energy.
		"""
		state = self.__state_vector[1]
		if state == self.State.main_region_at__work_working_at__shift_energy_tiring:
			self.__exit_sequence_main_region__at__work_working__at__shift_energy__tiring()
		
	def __exit_sequence_main_region__at__work_working__at__shift_button(self):
		"""Default exit sequence for region button.
		"""
		state = self.__state_vector[2]
		if state == self.State.main_region_at__work_working_at__shift_button_button_released:
			self.__exit_sequence_main_region__at__work_working__at__shift_button_button_released()
		elif state == self.State.main_region_at__work_working_at__shift_button_button_pressed:
			self.__exit_sequence_main_region__at__work_working__at__shift_button_button_pressed()
		elif state == self.State.main_region_at__work_working_at__shift_button_button_activated:
			self.__exit_sequence_main_region__at__work_working__at__shift_button_button_activated()
		
	def __exit_sequence_main_region__at__work_working__grace__period_r1(self):
		"""Default exit sequence for region r1.
		"""
		state = self.__state_vector[0]
		if state == self.State.main_region_at__work_working_grace__period_r1_alternative__chosen:
			self.__exit_sequence_main_region__at__work_working__grace__period_r1__alternative__chosen()
		elif state == self.State.main_region_at__work_working_grace__period_r1_in_grace:
			self.__exit_sequence_main_region__at__work_working__grace__period_r1_in_grace()
		
	def __react_main_region__at__work_working__at__shift_shift__choice_0(self):
		"""The reactions of state null..
		"""
		if self.__check_main_region__at__work_working__at__shift_shift__choice_0_tr0_tr0():
			self.__effect_main_region__at__work_working__at__shift_shift__choice_0_tr0()
		elif self.__check_main_region__at__work_working__at__shift_shift__choice_0_tr1_tr1():
			self.__effect_main_region__at__work_working__at__shift_shift__choice_0_tr1()
		else:
			self.__effect_main_region__at__work_working__at__shift_shift__choice_0_tr2()
		
	def __react_main_region__entry__default(self):
		"""Default react sequence for initial entry .
		"""
		self.__enter_sequence_main_region__at__home_default()
		
	def __react_main_region__at__work_working__at__shift_shift__unloading_main__entry__default(self):
		"""Default react sequence for initial entry .
		"""
		self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_default()
		
	def __react_main_region__at__work_working__at__shift_shift__entry__default(self):
		"""Default react sequence for initial entry .
		"""
		self.__react_main_region__at__work_working__at__shift_shift__choice_0()
		
	def __react_main_region__at__work_working__at__shift_shift__assembly_r1__entry__default(self):
		"""Default react sequence for initial entry .
		"""
		self.__enter_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__at_stock_default()
		
	def __react_main_region__at__work_working__at__shift_shift__loading_r1__entry__default(self):
		"""Default react sequence for initial entry .
		"""
		self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_default()
		
	def __react_main_region__at__work_working__at__shift_shift_hist(self):
		"""Default react sequence for shallow history entry hist.
		"""
		#Enter the region with shallow history
		if self.__history_vector[0] is not self.State.null_state:
			self.__shallow_enter_sequence_main_region__at__work_working__at__shift_shift()
		else:
			self.__react_main_region__at__work_working__at__shift_shift__choice_0()
		
	def __react_main_region__at__work_working__at__shift_energy__entry__default(self):
		"""Default react sequence for initial entry .
		"""
		self.__enter_sequence_main_region__at__work_working__at__shift_energy__tiring_default()
		
	def __react_main_region__at__work_working__at__shift_button__entry__default(self):
		"""Default react sequence for initial entry .
		"""
		self.__enter_sequence_main_region__at__work_working__at__shift_button_button_released_default()
		
	def __react_main_region__at__work_working__entry__default(self):
		"""Default react sequence for initial entry .
		"""
		self.__enter_sequence_main_region__at__work_working__grace__period_default()
		
	def __react_main_region__at__work_working__grace__period_r1__entry__default(self):
		"""Default react sequence for initial entry .
		"""
		self.__enter_sequence_main_region__at__work_working__grace__period_r1_in_grace_default()
		
	def __react(self):
		"""Implementation of __react function.
		"""
		return False
	
	
	def __main_region__at__home_react(self, try_transition):
		"""Implementation of __main_region__at__home_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.employee.go_to_work:
				self.__exit_sequence_main_region__at__home()
				self.__enter_sequence_main_region__at__work_default()
				self.__react()
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__react()
		return did_transition
	
	
	def __main_region__at__work_react(self, try_transition):
		"""Implementation of __main_region__at__work_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.__time_events[0]:
				self.__exit_sequence_main_region__at__work()
				self.__enter_sequence_main_region__shift_end_default()
				self.__react()
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__react()
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_react function.
		"""
		did_transition = try_transition
		if try_transition:
			did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__unloading_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__unloading_react function.
		"""
		did_transition = try_transition
		if try_transition:
			did_transition = False
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__unloading_main__at_stock_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__unloading_main__at_stock_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if ("Walk" is None) if (self.__current_action is None) else (self.__current_action == "Walk"):
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock()
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck_default()
				self.__main_region__at__work_working__at__shift_shift__unloading_react(False)
			elif (self.ui.action_pressed) and (("Toilet Break" is None) if (self.ui.action_pressed_value is None) else (self.ui.action_pressed_value == "Toilet Break")):
				self.__exit_sequence_main_region__at__work_working__at__shift()
				self.__enter_sequence_main_region__at__work_working__toilet__break_default()
				self.__main_region__at__work_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_shift__unloading_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__unloading_main__at_truck_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__unloading_main__at_truck_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if ("Pickup" is None) if (self.__current_action is None) else (self.__current_action == "Pickup"):
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck()
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying_default()
				self.__main_region__at__work_working__at__shift_shift__unloading_react(False)
			elif ("Walk" is None) if (self.__current_action is None) else (self.__current_action == "Walk"):
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck()
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_default()
				self.__main_region__at__work_working__at__shift_shift__unloading_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_shift__unloading_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if ("Walk" is None) if (self.__current_action is None) else (self.__current_action == "Walk"):
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying()
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying_default()
				self.__main_region__at__work_working__at__shift_shift__unloading_react(False)
			elif ("Drop" is None) if (self.__current_action is None) else (self.__current_action == "Drop"):
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying()
				self.factory.operation_callback.increase_material(1)
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_default()
				self.__main_region__at__work_working__at__shift_shift__unloading_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_shift__unloading_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if ("Walk" is None) if (self.__current_action is None) else (self.__current_action == "Walk"):
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying()
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying_default()
				self.__main_region__at__work_working__at__shift_shift__unloading_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_shift__unloading_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__assembly_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__assembly_react function.
		"""
		did_transition = try_transition
		if try_transition:
			did_transition = False
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__assembly_r1__at_stock_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__assembly_r1__at_stock_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if ("Assemble" is None) if (self.__current_action is None) else (self.__current_action == "Assemble") and self.factory.operation_callback.get_material() > 0:
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__at_stock()
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__assemble_default()
				self.__main_region__at__work_working__at__shift_shift__assembly_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_shift__assembly_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__assembly_r1__assemble_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__assembly_r1__assemble_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.__time_events[1]:
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__assemble()
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__assembly_r1__at_stock_default()
				self.__main_region__at__work_working__at__shift_shift__assembly_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_shift__assembly_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__loading_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__loading_react function.
		"""
		did_transition = try_transition
		if try_transition:
			did_transition = False
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__loading_r1__at_truck_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__loading_r1__at_truck_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if ("Walk" is None) if (self.__current_action is None) else (self.__current_action == "Walk"):
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck()
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_default()
				self.__main_region__at__work_working__at__shift_shift__loading_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_shift__loading_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__loading_r1__at_stock_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__loading_r1__at_stock_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if ("Pickup" is None) if (self.__current_action is None) else (self.__current_action == "Pickup") and self.factory.operation_callback.get_finished() > 0:
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock()
				self.factory.operation_callback.increase_finished(-1)
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying_default()
				self.__main_region__at__work_working__at__shift_shift__loading_react(False)
			elif ("Walk" is None) if (self.__current_action is None) else (self.__current_action == "Walk"):
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock()
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_default()
				self.__main_region__at__work_working__at__shift_shift__loading_react(False)
			elif (self.ui.action_pressed) and (("Toilet Break" is None) if (self.ui.action_pressed_value is None) else (self.ui.action_pressed_value == "Toilet Break")):
				self.__exit_sequence_main_region__at__work_working__at__shift()
				self.__enter_sequence_main_region__at__work_working__toilet__break_default()
				self.__main_region__at__work_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_shift__loading_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if ("Walk" is None) if (self.__current_action is None) else (self.__current_action == "Walk"):
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying()
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying_default()
				self.__main_region__at__work_working__at__shift_shift__loading_react(False)
			elif ("Drop" is None) if (self.__current_action is None) else (self.__current_action == "Drop"):
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying()
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_default()
				self.__main_region__at__work_working__at__shift_shift__loading_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_shift__loading_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if ("Walk" is None) if (self.__current_action is None) else (self.__current_action == "Walk"):
				self.__exit_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying()
				self.__enter_sequence_main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying_default()
				self.__main_region__at__work_working__at__shift_shift__loading_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_shift__loading_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_energy__tiring_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_energy__tiring_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.__time_events[2]:
				self.__exit_sequence_main_region__at__work_working__at__shift_energy__tiring()
				self.employee.operation_callback.increase_energy(-2)
				self.__enter_sequence_main_region__at__work_working__at__shift_energy__tiring_default()
			else:
				did_transition = False
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_button_button_released_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_button_button_released_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.ui.action_pressed:
				self.__exit_sequence_main_region__at__work_working__at__shift_button_button_released()
				self.__enter_sequence_main_region__at__work_working__at__shift_button_button_pressed_default()
				self.__main_region__at__work_working__at__shift_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_button_button_pressed_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_button_button_pressed_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.ui.action_released:
				self.__exit_sequence_main_region__at__work_working__at__shift_button_button_pressed()
				self.__enter_sequence_main_region__at__work_working__at__shift_button_button_released_default()
				self.__main_region__at__work_working__at__shift_react(False)
			elif self.__time_events[3]:
				self.__exit_sequence_main_region__at__work_working__at__shift_button_button_pressed()
				self.__enter_sequence_main_region__at__work_working__at__shift_button_button_activated_default()
				self.__main_region__at__work_working__at__shift_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__at__shift_button_button_activated_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__at__shift_button_button_activated_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.ui.action_released:
				self.__exit_sequence_main_region__at__work_working__at__shift_button_button_activated()
				self.__enter_sequence_main_region__at__work_working__at__shift_button_button_released_default()
				self.__main_region__at__work_working__at__shift_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__at__shift_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__toilet__break_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__toilet__break_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if (self.ui.action_pressed) and (("Done" is None) if (self.ui.action_pressed_value is None) else (self.ui.action_pressed_value == "Done")):
				self.__exit_sequence_main_region__at__work_working__toilet__break()
				self.__entry_action_main_region__at__work_working__at__shift()
				self.__react_main_region__at__work_working__at__shift_shift_hist()
				self.__enter_sequence_main_region__at__work_working__at__shift_energy_default()
				self.__enter_sequence_main_region__at__work_working__at__shift_button_default()
				self.__main_region__at__work_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__leave__day_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__leave__day_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.__time_events[4]:
				self.__exit_sequence_main_region__at__work()
				self.__enter_sequence_main_region__at__home_default()
				self.__react()
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__grace__period_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__grace__period_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.__time_events[5]:
				self.__exit_sequence_main_region__at__work_working__grace__period()
				self.__enter_sequence_main_region__at__work_working__at__shift_default()
				self.__main_region__at__work_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__grace__period_r1__alternative__chosen_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__grace__period_r1__alternative__chosen_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.employee.go_home:
				self.__exit_sequence_main_region__at__work_working__grace__period()
				self.__enter_sequence_main_region__at__work_working__leave__day_default()
				self.__main_region__at__work_react(False)
			elif self.employee.shift_clicked:
				self.__exit_sequence_main_region__at__work_working__grace__period_r1__alternative__chosen()
				self.__enter_sequence_main_region__at__work_working__grace__period_r1__alternative__chosen_default()
				self.__main_region__at__work_working__grace__period_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__grace__period_react(try_transition)
		return did_transition
	
	
	def __main_region__at__work_working__grace__period_r1_in_grace_react(self, try_transition):
		"""Implementation of __main_region__at__work_working__grace__period_r1_in_grace_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.employee.shift_clicked:
				self.__exit_sequence_main_region__at__work_working__grace__period_r1_in_grace()
				self.__enter_sequence_main_region__at__work_working__grace__period_r1__alternative__chosen_default()
				self.__main_region__at__work_working__grace__period_react(False)
			elif self.employee.go_home:
				self.__exit_sequence_main_region__at__work_working__grace__period()
				self.__enter_sequence_main_region__at__work_working__leave__day_default()
				self.__main_region__at__work_react(False)
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__main_region__at__work_working__grace__period_react(try_transition)
		return did_transition
	
	
	def __main_region__shift_end_react(self, try_transition):
		"""Implementation of __main_region__shift_end_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.employee.operation_callback.get_energy() < 25:
				self.__exit_sequence_main_region__shift_end()
				self.__enter_sequence_main_region__leave_tired_default()
				self.__react()
			elif self.__time_events[6]:
				self.__exit_sequence_main_region__shift_end()
				self.__enter_sequence_main_region__at__work_default()
				self.__react()
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__react()
		return did_transition
	
	
	def __main_region__leave_tired_react(self, try_transition):
		"""Implementation of __main_region__leave_tired_react function.
		"""
		did_transition = try_transition
		if try_transition:
			if self.__time_events[7]:
				self.__exit_sequence_main_region__leave_tired()
				self.__enter_sequence_main_region__at__home_default()
				self.__react()
			else:
				did_transition = False
		if not did_transition:
			did_transition = self.__react()
		return did_transition
	
	
	def __clear_in_events(self):
		"""Implementation of __clear_in_events function.
		"""
		self.employee.go_to_work = False
		self.employee.go_home = False
		self.employee.shift_clicked = False
		self.ui.action_pressed = False
		self.ui.action_released = False
		self.__time_events[0] = False
		self.__time_events[1] = False
		self.__time_events[2] = False
		self.__time_events[3] = False
		self.__time_events[4] = False
		self.__time_events[5] = False
		self.__time_events[6] = False
		self.__time_events[7] = False
	
	
	def enter(self):
		"""Implementation of enter function.
		"""
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.util.operation_callback is None:
			raise ValueError("Operation callback for interface Util must be set.")
		
		if self.employee.operation_callback is None:
			raise ValueError("Operation callback for interface Employee must be set.")
		
		if self.factory.operation_callback is None:
			raise ValueError("Operation callback for interface Factory must be set.")
		
		if self.ui.operation_callback is None:
			raise ValueError("Operation callback for interface Ui must be set.")
		
		if self.__is_executing:
			return
		self.__is_executing = True
		self.__enter_sequence_main_region_default()
		self.__is_executing = False
	
	
	def exit(self):
		"""Implementation of exit function.
		"""
		if self.__is_executing:
			return
		self.__is_executing = True
		self.__exit_sequence_main_region()
		self.__is_executing = False
	
	
	def run_cycle(self):
		"""Implementation of run_cycle function.
		"""
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.util.operation_callback is None:
			raise ValueError("Operation callback for interface Util must be set.")
		
		if self.employee.operation_callback is None:
			raise ValueError("Operation callback for interface Employee must be set.")
		
		if self.factory.operation_callback is None:
			raise ValueError("Operation callback for interface Factory must be set.")
		
		if self.ui.operation_callback is None:
			raise ValueError("Operation callback for interface Ui must be set.")
		
		if self.__is_executing:
			return
		self.__is_executing = True
		next_event = self.__get_next_event()
		if next_event is not None:
			self.__execute_queued_event(next_event)
		condition_0 = True
		while condition_0:
			self.__next_state_index = 0
			while self.__next_state_index < len(self.__state_vector):
				if self.__state_vector[self.__next_state_index] == self.State.main_region_at__home:
					self.__main_region__at__home_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock:
					self.__main_region__at__work_working__at__shift_shift__unloading_main__at_stock_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck:
					self.__main_region__at__work_working__at__shift_shift__unloading_main__at_truck_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_stock_carrying:
					self.__main_region__at__work_working__at__shift_shift__unloading_main__at_stock_carrying_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_shift_unloading_main_at_truck_carrying:
					self.__main_region__at__work_working__at__shift_shift__unloading_main__at_truck_carrying_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_shift_assembly_r1_at_stock:
					self.__main_region__at__work_working__at__shift_shift__assembly_r1__at_stock_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_shift_assembly_r1_assemble:
					self.__main_region__at__work_working__at__shift_shift__assembly_r1__assemble_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck:
					self.__main_region__at__work_working__at__shift_shift__loading_r1__at_truck_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock:
					self.__main_region__at__work_working__at__shift_shift__loading_r1__at_stock_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_truck_carrying:
					self.__main_region__at__work_working__at__shift_shift__loading_r1__at_truck_carrying_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_shift_loading_r1_at_stock_carrying:
					self.__main_region__at__work_working__at__shift_shift__loading_r1__at_stock_carrying_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_energy_tiring:
					self.__main_region__at__work_working__at__shift_energy__tiring_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_button_button_released:
					self.__main_region__at__work_working__at__shift_button_button_released_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_button_button_pressed:
					self.__main_region__at__work_working__at__shift_button_button_pressed_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_at__shift_button_button_activated:
					self.__main_region__at__work_working__at__shift_button_button_activated_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_toilet__break:
					self.__main_region__at__work_working__toilet__break_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_leave__day:
					self.__main_region__at__work_working__leave__day_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_grace__period_r1_alternative__chosen:
					self.__main_region__at__work_working__grace__period_r1__alternative__chosen_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_at__work_working_grace__period_r1_in_grace:
					self.__main_region__at__work_working__grace__period_r1_in_grace_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_shift_end:
					self.__main_region__shift_end_react(True)
				elif self.__state_vector[self.__next_state_index] == self.State.main_region_leave_tired:
					self.__main_region__leave_tired_react(True)
				self.__next_state_index += 1
			self.__clear_in_events()
			next_event = self.__get_next_event()
			if next_event is not None:
				self.__execute_queued_event(next_event)
			condition_0 = self.employee.go_to_work or self.employee.go_home or self.employee.shift_clicked or self.ui.action_pressed or self.ui.action_released or self.__time_events[0] or self.__time_events[1] or self.__time_events[2] or self.__time_events[3] or self.__time_events[4] or self.__time_events[5] or self.__time_events[6] or self.__time_events[7]
		self.__is_executing = False
	
	
	
